export function mountSimplePendulum(root: HTMLElement) {
  root.innerHTML = `<div class="pendulum-layout"><div class="pendulum-stage"><canvas></canvas></div><div class="pendulum-controls">${lengthControl(1,100,"lightblue")}${lengthControl(2,400,"lightgreen")}<div class="pendulum-button"><button type="button" data-start>Start</button></div><div class="pendulum-button"><button type="button" data-reset>Reset</button></div></div></div>`;
  const stage=root.querySelector<HTMLElement>(".pendulum-stage")!,canvas=root.querySelector<HTMLCanvasElement>("canvas")!,ctx=canvas.getContext("2d")!;
  const lengths=[100,400], theta=[.2,.2], velocity=[0,0]; let frame=0,running=false;
  function resize(){const d=devicePixelRatio||1,w=stage.clientWidth,h=w*2/3;stage.style.height=`${h}px`;canvas.width=w*d;canvas.height=h*d;canvas.style.width=`${w}px`;canvas.style.height=`${h}px`;ctx.setTransform(d,0,0,d,0,0);draw()}
  function draw(){const w=canvas.clientWidth,h=canvas.clientHeight;ctx.clearRect(0,0,w,h);lengths.forEach((length,i)=>{const x=w/2-length*Math.sin(theta[i]),y=length*Math.cos(theta[i]);ctx.beginPath();ctx.moveTo(w/2,0);ctx.lineTo(x,y);ctx.strokeStyle="#aaa";ctx.lineWidth=1;ctx.stroke();ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.fillStyle=i?"lightgreen":"lightblue";ctx.fill()});ctx.fillStyle="#000";ctx.beginPath();ctx.arc(w/2,0,1,0,Math.PI*2);ctx.fill()}
  function animate(){if(!running||!root.isConnected)return;lengths.forEach((length,i)=>{velocity[i]+=-9.8*theta[i]*.1/length;theta[i]+=velocity[i]});draw();frame=requestAnimationFrame(animate)}
  root.querySelectorAll<HTMLInputElement>("[data-length]").forEach(input=>{const i=Number(input.dataset.length)-1,num=root.querySelector<HTMLInputElement>(`[data-length-number="${i+1}"]`)!;const update=(v:number)=>{lengths[i]=Math.max(50,Math.min(500,v));input.value=num.value=String(lengths[i]);input.style.setProperty("--range-progress",`${(lengths[i]-50)/4.5}%`);draw()};input.addEventListener("input",()=>update(Number(input.value)));num.addEventListener("change",()=>update(Number(num.value)));update(lengths[i])});
  const fields=[...root.querySelectorAll<HTMLInputElement>("input")],start=root.querySelector<HTMLButtonElement>("[data-start]")!;
  start.addEventListener("click",()=>{if(running)return;running=true;fields.forEach(x=>x.disabled=true);start.disabled=true;frame=requestAnimationFrame(animate)});
  root.querySelector<HTMLButtonElement>("[data-reset]")!.addEventListener("click",()=>{running=false;cancelAnimationFrame(frame);theta[0]=theta[1]=.2;velocity[0]=velocity[1]=0;fields.forEach(x=>x.disabled=false);start.disabled=false;draw()});
  new ResizeObserver(resize).observe(stage);resize();
}
function lengthControl(i:number,v:number,color:string){return `<div class="pendulum-control"><label for="pendulum-${i}">Pendulum ${i} Length</label><div><input id="pendulum-${i}" data-length-number="${i}" type="number" min="50" max="500" value="${v}"><span>pixels</span></div><input data-length="${i}" type="range" min="50" max="500" step="1" value="${v}" style="--range-color:${color}"></div>`}
